import mongoose from "mongoose";
import sequence from "mongoose-sequence";

const adminSchema = new mongoose.Schema({
  // ID field is auto-generated by mongo db and is not required to be defined in the schema
  // _id: {
  //   type: Number,
  //   required: true,
  // },
  firstName: {
    type: String,
    required: true,
  },
  lastName: {
    type: String,
  },
  emailAddress: {
    type: String,
    required: true,
    validate: {
      validator: function (v) {
        // validate email address
        return /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(v);
      },
      message: (props) => `${props.value} is not a valid email address!`,
    },
    lowercase: true,
  },
  password: {
    type: String,
    required: true,
  },
  contactNumber: {
    type: String,
    default: "",
  },
  permissions: {
    type: [String],
    enum: ["super", "admin", "logistics"],
    // Let me know if these permissions are enough or if we need to add more
    // super: can do everything
    // admin: can validate or invalidate users but not create / delete
    // logistics: can only do scheduling and handling deliveries

    required: true, // Should be required
  },
  createdAt: {
    type: Date,
    immutable: true,
    default: () => Date.now(),
  },
  updatedAt: {
    type: Date,
    default: () => Date.now(),
  },
});

// We could add a createdAt and updatedAt field to the schema if we want to track the order of creation and last update of each object instead of using increment in the ID field
// adminSchema.plugin(sequence, { inc_field: "_id" });

// Update the updatedAt field before saving the document
adminSchema.pre("save", function (next) {
  this.updatedAt = Date.now();
  next();
});

const Admin = mongoose.model("Admin", adminSchema);

export default Admin;
